apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Kubernetes DNS name — works because Grafana and Prometheus are in the same namespace
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
